### ISSUE TITLE
`hyper` conflict

### ISSUE THREAD

**Issue by bspeice** [marad/hyper-router#6]
Depending on the `hyper` crate, and this crate, introduces a conflict since this crate is using hyper 0.7.2, whereas the recent stable `hyper` is 0.9.0. Can this be re-released (and potentially updated) to use the newer version?

**Comment by marad** [comment]
I've created version 0.1.3 with dependency to hyper 0.9.10.

**Comment by cardoe** [comment]
Can you yank `hyper-router` 0.1.3 and re-release it as `hyper-router` 0.2.0? You've broken semver that the Rust community really tries to champion because the APIs that `hyper-router` exposes aren't compatible because it uses types from `hyper`.

**Comment by cardoe** [comment]
I guess its as simple as changing my `Cargo.toml` to now depend on `hyper` 0.9.10. But all this seems a little kludgy and breaky because a `cargo update` shouldn't fail to compile but instead should work. Really this should still get bumped as a new API level since it requires a change in the end user's `Cargo.toml`.

**Comment by marad** [comment]
Yanked the 1.3.0 and republished as 0.2.0, thanks for the info!
